spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:admin@localhost:27017/app?authSource=admin}

server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui

jwt:
  secret: ${JWT_SECRET:your-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm-make-it-secure}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION:900000}  # 15 minutes in milliseconds
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 7 days in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always